/*
  Self-checking testbench for the Timer-Core FPGA wrapper.

  Nothing is driven but the clock and the reset button: the wrapper's own
  control unit has to program the register file, poll the timer and toggle the
  LED. The testbench checks
    1. that the register file was programmed with the compile-time parameters,
    2. that the Counter really is read over AXI-Lite, watched on the bus,
    3. that the LED toggles once per (TOGGLE_VALUE + 1) * (PRESCALER + 1)
       cycles and that only the LED_COLOUR channels ever light.
*/
`timescale 1ns / 1ps

`ifndef DEBUG
`define DEBUG 0
`endif

module timer_fpga_tb ();

  // --------------------------------------------------------------------------
  // Parameters
  // --------------------------------------------------------------------------
  // Small enough to simulate, large enough that a match cannot be missed by
  // the poll loop. The board defaults are checked separately on dut_default.
  localparam integer Prescaler = 1;
  localparam integer ToggleValue = 24;
  localparam integer LedPeriod = (ToggleValue + 1) * (Prescaler + 1);  // 50 cycles

  // Board defaults: one LED toggle per second off the 25 MHz oscillator.
  localparam integer BoardClkHz = 25_000_000;
  localparam integer BoardToggleValue = BoardClkHz - 1;
  localparam integer BoardPrescaler = 0;

  // MMIO byte address of the Counter register, watched on the AXI-Lite bus.
  localparam logic [31:0] RegCounterAddr = 32'h10;

  // Board LED wiring, mirroring the wrapper defaults: blue only, common
  // cathode, so a channel is dark at 0 and lit at 1.
  localparam logic [2:0] LedColour = 3'b001;
  localparam bit LedActiveLow = 1'b0;
  localparam logic LedDark = LedActiveLow;

  // Cycles the control unit may need to notice a match: RdCnt -> RdCntD ->
  // RdSt -> RdStD -> ClrCmd -> ClrResp, plus AXI-Lite wait states.
  localparam integer DetectLatency = 12;

  localparam integer NToggles = 9;
  localparam integer VERBOSE = `DEBUG;
  localparam integer MaxRunTime = 4000;

  // --------------------------------------------------------------------------
  // Clock / reset
  // --------------------------------------------------------------------------
  logic clk_i = 0;
  logic arst = 1;
  always #5 clk_i = ~clk_i;

  // --------------------------------------------------------------------------
  // Scoreboard
  // --------------------------------------------------------------------------
  integer errors = 0;
  integer checks = 0;

  // Held low until the design is known to be running, so the settle on led_o at
  // power up is not counted as an LED edge.
  logic        monitor_en = 1'b0;

  // Monitor registers, all generated by reg.py: the testbench has no
  // hand-written sequential logic. The declarations carry the value each one
  // holds before the first clock edge. Only the first and last LED edge are
  // kept, which is all the span needs, so no array is required.
  logic [31:0] cycles = '0;
  logic [31:0] cycles_n;
  logic        led_prev = 1'b0;
  logic        led_prev_n;
  logic [31:0] toggles = '0;
  logic [31:0] toggles_n;
  logic [31:0] first_toggle_cycle = '0;
  logic [31:0] first_toggle_cycle_n;
  logic [31:0] last_toggle_cycle = '0;
  logic [31:0] last_toggle_cycle_n;
  logic [31:0] counter_reads = '0;
  logic [31:0] counter_reads_n;
  logic [31:0] counter_read_bad = '0;
  logic [31:0] counter_read_bad_n;
  logic [31:0] rgb_wrong_channel = '0;
  logic [31:0] rgb_wrong_channel_n;
  logic [31:0] led_lit_cycles = '0;
  logic [31:0] led_lit_cycles_n;
  logic        pending_counter_read = 1'b0;
  logic        pending_counter_read_n;

  // Register controls
  logic        mon_reads;
  logic        mon_hold;
  logic        mon_active;
  logic        led_toggled;
  logic        first_toggle_en;
  logic        last_toggle_en;
  logic        counter_read_done;
  logic        counter_ar_accept;
  logic        pending_counter_read_en;
  logic        counter_read_bad_en;
  logic        rgb_wrong;
  logic        led_lit;

  // --------------------------------------------------------------------------
  // DUT
  // --------------------------------------------------------------------------
  logic led_r_o;
  logic led_g_o;
  logic led_b_o;
  // The selected channel stands in for the LED.
  wire  led_o = led_b_o;

  timer_fpga #(
      .CLK_FREQ_HZ (25_000_000),
      .PRESCALER   (Prescaler),
      .TOGGLE_VALUE(ToggleValue)
  ) dut (
      .clk_i      (clk_i),
      .arst_i (arst),
      .led_r_o(led_r_o),
      .led_g_o(led_g_o),
      .led_b_o(led_b_o)
  );

  // A second wrapper left on its defaults. Simulating a whole second is
  // impractical, so only its init sequence is checked: if the defaults stop
  // meaning "one toggle per second", Compare comes out wrong here.
  logic led_r_default_o;
  logic led_g_default_o;
  logic led_b_default_o;

  timer_fpga dut_default (
      .clk_i      (clk_i),
      .arst_i (arst),
      .led_r_o(led_r_default_o),
      .led_g_o(led_g_default_o),
      .led_b_o(led_b_default_o)
  );

  // --------------------------------------------------------------------------
  // Monitors
  // --------------------------------------------------------------------------
  // LED edges. led_prev simply follows led_o, so comparing the two spots an
  // edge; the count and the two recorded cycles restart whenever the monitor
  // is held, which is during reset and before it is armed.
  assign mon_reads   = ~arst;
  assign mon_hold    = arst | ~monitor_en;
  assign mon_active  = ~arst & monitor_en;
  assign led_prev_n  = led_o;
  assign led_toggled = mon_active & (led_o !== led_prev);

  assign cycles_n             = cycles + 1'b1;
  assign toggles_n            = toggles + 1'b1;
  assign first_toggle_en      = led_toggled & (toggles == 32'd0);
  assign last_toggle_en       = led_toggled & (toggles < NToggles);
  assign first_toggle_cycle_n = cycles;
  assign last_toggle_cycle_n  = cycles;

  // Watch the AXI-Lite port for Counter reads. The control unit does not latch
  // the value, so the bus transaction is the only evidence it reads the timer:
  // pending_counter_read remembers that the accepted address phase was aimed
  // at Counter, and the read data beat one cycle later is counted and range
  // checked.
  assign counter_read_done       = mon_reads & dut.t_rvalid & pending_counter_read;
  assign counter_ar_accept       = mon_reads & ~counter_read_done
                                 & dut.t_arvalid & dut.t_arready;
  assign pending_counter_read_en = counter_read_done | counter_ar_accept;
  assign pending_counter_read_n  = counter_ar_accept & (dut.t_araddr == RegCounterAddr);
  assign counter_reads_n         = counter_reads + 1'b1;
  assign counter_read_bad_n      = counter_read_bad + 1'b1;
  assign counter_read_bad_en     = counter_read_done & (dut.t_rdata > ToggleValue);

  // Channels outside LED_COLOUR must stay dark all run, or the LED mixes into
  // another colour. Blue is the only selected channel here.
  assign rgb_wrong           = mon_active & ((led_r_o !== LedDark) | (led_g_o !== LedDark));
  assign rgb_wrong_channel_n = rgb_wrong_channel + 1'b1;
  assign led_lit             = mon_active & (led_b_o !== LedDark);
  assign led_lit_cycles_n    = led_lit_cycles + 1'b1;

  `include "reg_timer_fpga_tb_monitors.vs"  /*
    cycles              , 32, 0,         ,                        , _n
    led_prev            ,  1, 0,         ,                        , _n
    toggles             , 32, 0, mon_hold, led_toggled             , _n
    first_toggle_cycle  , 32, 0, mon_hold, first_toggle_en         , _n
    last_toggle_cycle   , 32, 0, mon_hold, last_toggle_en          , _n
    pending_counter_read,  1, 0, arst    , pending_counter_read_en , _n
    counter_reads       , 32, 0,         , counter_read_done       , _n
    counter_read_bad    , 32, 0,         , counter_read_bad_en     , _n
    rgb_wrong_channel   , 32, 0,         , rgb_wrong               , _n
    led_lit_cycles      , 32, 0,         , led_lit                 , _n
    */

  // --------------------------------------------------------------------------
  // Scoreboard helpers
  // --------------------------------------------------------------------------
  task automatic check_val(input string name, input logic [31:0] got,
                           input logic [31:0] exp);
    begin
      checks = checks + 1;
      if (got !== exp) begin
        errors = errors + 1;
        $display("[%0t] FAIL %-30s got %0d expected %0d", $time, name, got, exp);
      end else if (VERBOSE) begin
        $display("[%0t] pass %-30s %0d", $time, name, got);
      end
    end
  endtask

  task automatic check_min(input string name, input integer got, input integer min);
    begin
      checks = checks + 1;
      if (got < min) begin
        errors = errors + 1;
        $display("[%0t] FAIL %-30s got %0d expected >= %0d", $time, name, got, min);
      end else if (VERBOSE) begin
        $display("[%0t] pass %-30s %0d", $time, name, got);
      end
    end
  endtask

  // --------------------------------------------------------------------------
  // Main stimulus
  // --------------------------------------------------------------------------
  integer measured;
  integer expected;
  integer traced;

  initial begin
    $display("==================================================");
    $display(" timer_fpga testbench (TOGGLE_VALUE = %0d, PRESCALER = %0d)", ToggleValue,
             Prescaler);
    $display("==================================================");

    // The reset button is never pressed: this is the board scenario, where the
    // pin idles de-asserted and only the power-on reset starts the design.
    arst = 1'b0;
    repeat (4) @(negedge clk_i);

    // The LED must start off.
    check_val("LED off after power-on reset", {31'b0, led_o}, {31'b0, LedDark});

    // Give the power-on reset time to expire, then the control unit time to
    // walk its init sequence.
    repeat (60) @(negedge clk_i);
    $display("-- Init sequence --");
    check_val("Prescaler programmed", {16'b0, dut.timer_0.Prescaler}, Prescaler);
    check_val("Compare programmed", dut.timer_0.Compare, ToggleValue);
    check_val("Control programmed", {24'b0, dut.timer_0.Control}, 32'h3);

    // The default build must program a one second period.
    check_val("default Prescaler", {16'b0, dut_default.timer_0.Prescaler}, BoardPrescaler);
    check_val("default Compare", dut_default.timer_0.Compare, BoardToggleValue);
    checks = checks + 1;
    if (((BoardToggleValue + 1) * (BoardPrescaler + 1)) != BoardClkHz) begin
      errors = errors + 1;
      $display("[%0t] FAIL default toggle period is not one second", $time);
    end else begin
      $display(" default toggle period: %0d cycles = 1.000 s at %0d Hz", BoardClkHz,
               BoardClkHz);
    end

    // Wait for NToggles LED edges.
    $display("-- LED toggling --");
    monitor_en = 1'b1;
    traced = 0;
    while (toggles < NToggles) begin
      @(negedge clk_i);
      if (VERBOSE && (toggles != traced)) begin
        $display("[%0t] LED edge %0d at cycle %0d", $time, toggles, last_toggle_cycle);
        traced = toggles;
      end
    end
    repeat (2) @(negedge clk_i);

    check_min("LED toggle count", toggles, NToggles);

    // Each toggle is one timer match, so the toggles must be one LED period
    // apart on average; the poll loop only adds a bounded detection latency.
    measured = last_toggle_cycle - first_toggle_cycle;
    expected = (NToggles - 1) * LedPeriod;
    checks   = checks + 1;
    if ((measured > expected + DetectLatency) || (measured < expected - DetectLatency)) begin
      errors = errors + 1;
      $display("[%0t] FAIL %-30s got %0d expected %0d +/- %0d", $time,
               "LED toggle span", measured, expected, DetectLatency);
    end else begin
      $display(" LED toggle span over %0d edges: %0d cycles (expected %0d)", NToggles - 1,
               measured, expected);
    end

    // Pressing the reset button must restart the whole wrapper: the LED goes
    // back to off and the control unit programs the register file again.
    $display("-- Reset button --");
    arst = 1'b1;
    repeat (4) @(negedge clk_i);
    check_val("LED held off during reset", {31'b0, led_o}, {31'b0, LedDark});
    check_val("Control cleared by reset", {24'b0, dut.timer_0.Control}, 32'h0);
    @(negedge clk_i);
    arst = 1'b0;
    // Re-init plus a full LED period before the next edge can appear.
    repeat (60 + 2 * LedPeriod) @(negedge clk_i);
    check_val("Compare reprogrammed", dut.timer_0.Compare, ToggleValue);
    check_val("Control reprogrammed", {24'b0, dut.timer_0.Control}, 32'h3);
    check_min("LED toggling again", toggles, 1);

    $display("-- Counter readback --");
    check_min("Counter reads on the bus", counter_reads, 8);
    check_val("Counter reads in range", counter_read_bad, 32'h0);

    $display("-- LED is blue or off --");
    check_val("red and green stay dark", rgb_wrong_channel, 32'h0);
    check_val("red channel dark", {31'b0, led_r_o}, {31'b0, LedDark});
    check_val("green channel dark", {31'b0, led_g_o}, {31'b0, LedDark});
    // The blue channel must actually have been lit for part of the run, or
    // "only blue ever lights" would pass on a permanently dark LED.
    check_min("blue channel lit cycles", led_lit_cycles, LedPeriod);

    repeat (4) @(negedge clk_i);
    $display("==================================================");
    $display(" Checks run : %0d", checks);
    $display(" Errors     : %0d", errors);
    if (errors == 0) $display(" RESULT     : PASS");
    else $display(" RESULT     : FAIL");
    $display("==================================================");
    $finish;
  end

  // Watchdog
  initial begin
    repeat (MaxRunTime) @(negedge clk_i);
    $display("[%0t] TIMEOUT: simulation did not finish in time", $time);
    $finish;
  end

  // Dump waves. Off by default; enable with `make sim-run VCD=1`.
`ifdef VCD
  initial begin
    $dumpfile("timer_fpga_tb.vcd");
    $dumpvars(0, timer_fpga_tb);
  end
`endif

endmodule
